### ISSUE TITLE
Image test

### ISSUE THREAD

**Issue by LuukSelen** [SirLANcel0t/CinemaApp#32]
![Cxe6f4nXUAA7Yeg](https://user-images.githubusercontent.com/20944676/110949147-8c4f0080-8342-11eb-9f94-30ad453f20f4.png)

**Comment by SirLANcel0t** [comment]
![use-case_cinema-page-001](https://user-images.githubusercontent.com/78827234/110949438-e059e500-8342-11eb-987d-a4cae858a6f0.jpg)
